# Generated by Django 5.2.17 on 2026-09-26 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdraw", "Withdraw"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                (
                    "amount",
                    models.BigIntegerField(
                        help_text="Positive amount in minor units for this operation."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_transactions",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "wallet_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transactions",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "wallet_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transactions",
                        to="wallets.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("TRANSFER_OUT", "Transfer out"),
                            ("TRANSFER_IN", "Transfer in"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("balance_after", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="wallets.wallet",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="ledger.ledgertransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["tenant", "created_at"], name="ledger_ledg_tenant__e397c5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgertransaction",
            constraint=models.UniqueConstraint(
                fields=("tenant", "idempotency_key"), name="uniq_tenant_idempotency_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgertransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="ledger_tx_amount_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["wallet", "created_at"], name="ledger_ledg_wallet__ac3b02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["tenant", "created_at"], name="ledger_ledg_tenant__e7dddb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="ledger_entry_amount_positive",
            ),
        ),
    ]
